import turtle
# Create a turtle object
t = turtle.Turtle()
# Set the screen background color
turtle.bgcolor("white")
t.speed(0)
t.color("black")
t.pensize(5)
t.penup()
t.goto(0, -200)
t.fillcolor("blue")
t.pendown()
t.begin_fill()
t.circle(200)
t.end_fill()
t.color("black")
t.pensize(5)
t.penup()
t.goto(0, -150)
t.fillcolor("white")
t.pendown()
t.begin_fill()
t.circle(150)
t.end_fill()
t.pensize(5)
t.penup()
t.goto(-75, 125)
t.fillcolor("blue")
t.pendown()
t.begin_fill()
t.right(50)
t.forward(293)
t.penup()
t.right(90)
t.forward(30)
t.pendown()
t.right(90)
t.forward(300)
t.right(90)
t.penup()
t.forward(30)
t.end_fill()
t.pensize(5)
t.penup()
t.goto(-80, 127)
t.color("blue")
t.pendown()
t.left(176)
t.forward(22)
t.penup()
t.pensize(5)
t.goto(110, -104)
t.color("blue")
t.pendown()
t.left(7)
t.forward(24)
t.hideturtle()
turtle.exitonclick()
